# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formulario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(295, 373)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.etiqueta_nombre = QtWidgets.QLabel(self.centralwidget)
        self.etiqueta_nombre.setGeometry(QtCore.QRect(40, 100, 49, 16))
        self.etiqueta_nombre.setObjectName("etiqueta_nombre")
        self.etiqueta_apellidos = QtWidgets.QLabel(self.centralwidget)
        self.etiqueta_apellidos.setGeometry(QtCore.QRect(40, 130, 49, 16))
        self.etiqueta_apellidos.setObjectName("etiqueta_apellidos")
        self.entrada_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_nombre.setGeometry(QtCore.QRect(120, 100, 113, 22))
        self.entrada_nombre.setObjectName("entrada_nombre")
        self.entrada_apellidos = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_apellidos.setGeometry(QtCore.QRect(120, 130, 113, 22))
        self.entrada_apellidos.setObjectName("entrada_apellidos")
        self.enviar = QtWidgets.QPushButton(self.centralwidget)
        self.enviar.setGeometry(QtCore.QRect(100, 190, 75, 24))
        self.enviar.setObjectName("enviar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.etiqueta_nombre.setText(_translate("MainWindow", "Nombre"))
        self.etiqueta_apellidos.setText(_translate("MainWindow", "Apellidos"))
        self.enviar.setText(_translate("MainWindow", "Enviar"))
